# This file is intentionally minimal.
# The Netlify Next.js plugin will automatically detect and apply the correct
# build command (`next build`) and publish directory (`.next`).

[[plugins]]
  package = "@netlify/plugin-nextjs"